### ISSUE TITLE
[BUG] band-solidity package isn't updated with mainnet oracle addresses 

### ISSUE THREAD

**Issue by touhonoob** [bandprotocol/band#350]

**Comment by taobun** [comment]
band-solidity currently in development phase. All function work well in mainnet. Please used `Oracle(0xD5D2b9e9bcd172D5fC8521AFd2C98Dd239F5b607)` instead of `FINANCIAL`. The new version of band-solidity that check network will publish soon.

**Comment by taobun** [comment]
band-solidity is currently in development phase. However all function work well in mainnet, just used Oracle(0xD5D2b9e9bcd172D5fC8521AFd2C98Dd239F5b607) instead of FINANCIAL. The new version of band-solidity that check network will publish soon.
