### ISSUE TITLE
Feature Request: Add Estimated Staking APR of Data Token to Governance Portal

### ISSUE THREAD

**Issue by touhonoob** [bandprotocol/band#358]
## Motivation
Currently there is no way for investors to know about the estimated staking APR of data tokens. Showing estimated staking APR will potentially increase the adoption of data tokens staking.

## Suggested Implementation
Estimated staking APR can be calculated based on the past staking reward distributions.

**Comment by sorawit** [comment]
Thanks for the suggestion! We have been working on that on a separate repo and will release an alternative interface to interact with Band Protocol that has estimated APR shorty. I'm closing this for now.
