### ISSUE TITLE
[BUG] Navbar social media links

### ISSUE THREAD

**Issue by smiled0g** [bandprotocol/band#75]
![image](https://user-images.githubusercontent.com/891585/63422179-1a4b5980-c434-11e9-8b58-ce387a0fa97b.png)

The social links on the navbar don't function as they're supposed to

1. Hovering on the background should do nothing (currently highlight, which makes it seems clickable)

2. Hovering on the logo should show a filled version of these
![image](https://user-images.githubusercontent.com/891585/63422386-744c1f00-c434-11e9-97e8-8537a71d6eb4.png)

3. Clicking on each logo should link to the corresponding social media channel

**Comment by evilpeach** [comment]
Didn't fixed it. Wrong commit
